fix: underscore crate name
ProbablyClem/utoipauto pull request #38
Opened 2024-08-12 21:58 UTC by EvolveArt

Resolves #37 

## Changes
- Adds the `replace` call as mentioned in the issue's comments

2024-08-13 04:24 UTC, DenuxPlays commented
Does normal crates name liked `normal-crate` still work?
I am not sure if this is tested?

2024-08-13 04:55 UTC, DenuxPlays requested changes
Unit test looks fine.
But I am missing an acceptance test.
I think we already have a test crate in the tests folder which could be extended.

2024-08-13 14:41 UTC, DenuxPlays commented
> > Unit test looks fine. But I am missing an acceptance test. I think we already have a test crate in the tests folder which could be extended.
> 
> 
> 
> Should I create another `create-segment-path` for instance ?  or just a `sub-folder` ?
> 
> 
> 
> EDIT: the issue is on the crate name, so the only acceptance test that could be done is by creating a new test crate
> 
> EDIT 2: the tests folder doesn't seem to be compiled anywhere

Yes just create another test crate.

I noticed this too so I already created a fix: https://github.com/ProbablyClem/utoipauto/pull/39

2024-08-13 17:21 UTC, EvolveArt commented
> > > Unit test looks fine. But I am missing an acceptance test. I think we already have a test crate in the tests folder which could be extended.
> > 
> > 
> > Should I create another `create-segment-path` for instance ?  or just a `sub-folder` ?
> > EDIT: the issue is on the crate name, so the only acceptance test that could be done is by creating a new test crate
> > EDIT 2: the tests folder doesn't seem to be compiled anywhere
> 
> Yes just create another test crate.
> 
> I noticed this too so I already created a fix: #39

Ok so I will rebase once your fix is merged

2024-08-15 11:06 UTC, DenuxPlays commented
@EvolveArt 

PRs have been merged you can now merge main into your branch and create the acceptance test

2024-08-15 23:47 UTC, EvolveArt commented
> @EvolveArt
> 
> PRs have been merged you can now merge main into your branch and create the acceptance test

Done, you can check. Not sure if that's the best way but it does provide a correct acceptance test. 
I think acceptance tests could be refactored in another PR.

2024-08-16 05:38 UTC, DenuxPlays commented on acceptance/Cargo.toml
> +members = ["crate_segment_path", "new_crate_segment_path"]
```suggestion
members = ["crate_segment_path", "folder_in_src"]
```

2024-08-16 05:38 UTC, DenuxPlays commented on acceptance/crate_segment_path/Cargo.toml
> +utoipauto-lib-test-new = { path = "../new_crate_segment_path" }
```suggestion
folder_in_src = { path = "../folder_in_src" }
```

2024-08-16 05:38 UTC, DenuxPlays commented on acceptance/new_crate_segment_path/Cargo.toml
> +name = "utoipauto-lib-test-new"
```suggestion
name = "folder_in_src"
```

2024-08-16 05:40 UTC, DenuxPlays requested changes
Please rename the folder and the name to `folder_in_src`
The name is more descriptive.

Otherwise your pr looks pretty good.
Thank you for your work :)

2024-08-16 10:29 UTC, EvolveArt commented
> Please rename the folder and the name to `folder_in_src` The name is more descriptive.
> 
> Otherwise your pr looks pretty good. Thank you for your work :)

Done :) looking forward to help more, this crate has been really useful to simplify our utoipa doc generation

2024-08-16 11:12 UTC, DenuxPlays approved these changes
Looks good to me

2024-08-16 11:40 UTC, DenuxPlays commented
Note:

I am not sure if we should introduce a "main" testing crate where we could merge all things that need to be tested across multiple crates (like this pr).
But this has nothing todo with this pr.
Just a small note from me.

Note 2:

I do have a plan for creating a larger test crate that tests multiple things maybe we can combine the ideas.

2024-08-16 11:55 UTC, DenuxPlays commented
@EvolveArt Could you rebase your pr one more time?
I fixed the ci a bit

2024-08-16 11:57 UTC, EvolveArt commented
> @EvolveArt Could you rebase your pr one more time? I fixed the ci a bit

done

2024-08-16 12:04 UTC, DenuxPlays approved these changes

2024-08-17 09:41 UTC, ProbablyClem commented
Thanks guy for your work

2024-08-17 09:41 UTC, merged